### PR TITLE
pivorak homework #1 variant #15 pattern ""123456-ZXCE-ABCD""

### PR DESCRIPTION
**Pull request by Sayok**

### CODE REVIEW

**Review by oleksandr-kychun — COMMENTED** [review]
Nice solution) how about "magic numbers" and "magic ranges"? any idea how to get rid of them?

**Comment by Sayok** [comment]
@ghostinshadow I've made some changes to the method. is that better now?

**Review by oleksandr-kychun — COMMENTED** [review]
Clever) i like it

**Review by sveredyuk — APPROVED** [review]
Якщо сам до ламд додумався, то молодець.

**Pull request closed without merging**
