### PR TITLE
added 19 method

### PR DESCRIPTION
**Pull request by HelenMaherovska**

### CODE REVIEW

**Review by oleksandr-kychun — COMMENTED** [review]
nice solution) one thing to think about - there are some 'magic numbers'

**Comment by HelenMaherovska** [comment]
@ghostinshadow Is it better now?

**Review by oleksandr-kychun — COMMENTED** [review]
Yes) that's better. you can apply this principle even to 'a'..'z' and  parameters to #sample method(2, 4, 2)

**Comment by HelenMaherovska** [comment]
@ghostinshadow I've fixed that)

**Review by oleksandr-kychun — COMMENTED** [review]
I like your refactoring) You've got rid of duplications

**Comment by HelenMaherovska** [comment]
Yep :)

**Comment by ruslan-369** [comment]
👍 for cool commit history

**Comment by HelenMaherovska** [comment]
@adrenalin23 :)

**Review by sveredyuk — APPROVED** [review]

**Pull request closed without merging**
